content = open('index.html', encoding='utf-8').read()
old = "                    ghost.addEventListener('click', function(e) {\n                        e.stopPropagation();\n                        if (window.descOpen) { window.hideDesc(); } else { window.showDesc(); }\n                    });"
new = "                    ghost.addEventListener('click', function(e) {\n                        e.stopPropagation();\n                        var d = document.getElementById('photo-description');\n                        var img = window.activeImg;\n                        var g = window.ghost;\n                        var cap = document.querySelector('.photo-caption-bar');\n                        if (!d || !img || !g) return;\n                        if (window.descOpen) {\n                            if (g._shift) { g.style.transform = g.style.transform.replace(' translateX(-' + g._shift + 'px)', ''); g._shift = null; }\n                            d.style.opacity = '0';\n                            if (cap) cap.style.opacity = '1';\n                            window.descOpen = false;\n                        } else {\n                            d.querySelector('.desc-title').textContent = img.dataset.title || '';\n                            d.querySelector('.desc-meta').textContent = (img.dataset.artist||'') + (img.dataset.year ? ' · '+img.dataset.year : '');\n                            d.querySelector('.desc-body').textContent = img.dataset.description || '';\n                            var panelW = Math.min(window.innerWidth * 0.28, 360);\n                            var shift = (panelW + 28) / 2;\n                            g.style.transform = g.style.transform + ' translateX(-' + shift + 'px)';\n                            g._shift = shift;\n                            d.style.cssText = 'position:fixed; top:50%; right:40px; width:' + panelW + 'px; transform:translateY(-50%); padding:40px 32px; color:white; z-index:10001; opacity:1; transition:opacity 300ms ease;';\n                            if (cap) cap.style.opacity = '0';\n                            window.descOpen = true;\n                        }\n                    });"
if old in content:
    content = content.replace(old, new, 1)
    open('index.html', 'w', encoding='utf-8').write(content)
    print('Done')
else:
    print('ERROR: old string not found')
