content = open('index.html', encoding='utf-8').read()
old = "            document.addEventListener('click', function(e) {\n                if (!ghost) return;\n                if (justOpened) { justOpened = false; return; }\n                const gr = ghost.getBoundingClientRect();\n                const insideGhost = e.clientX>=gr.left && e.clientX<=gr.right && e.clientY>=gr.top && e.clientY<=gr.bottom;\n                const pr = (descPanel && descOpen) ? descPanel.getBoundingClientRect() : null;\n                const insidePanel = pr && e.clientX>=pr.left && e.clientX<=pr.right && e.clientY>=pr.top && e.clientY<=pr.bottom;\n                if (insideGhost || insidePanel) {\n                    if (window.descOpen) { window.hideDesc(); } else { window.showDesc(); }\n                } else {\n                    if (descOpen) { descPanel.style.opacity='0'; descOpen=false; }\n                    collapse();\n                }\n            });"
new = "            document.addEventListener('click', function(e) {\n                if (!ghost) return;\n                if (justOpened) { justOpened = false; return; }\n                if (e.target === ghost || e.target.closest('#photo-description')) return;\n                if (window.descOpen) {\n                    window.descOpen = false;\n                    var dp = document.getElementById('photo-description');\n                    if (dp) dp.style.opacity = '0';\n                    var cap = document.querySelector('.photo-caption-bar');\n                    if (cap) cap.style.opacity = '1';\n                    if (ghost._shift) { ghost.style.transform = ghost.style.transform.replace(' translateX(-'+ghost._shift+'px)',''); ghost._shift = null; }\n                    return;\n                }\n                collapse();\n            });"
if old in content:
    content = content.replace(old, new, 1)
    open('index.html', 'w', encoding='utf-8').write(content)
    print('Done')
else:
    print('ERROR not found')
