import re

content = open('index.html', encoding='utf-8').read()

content = re.sub(r'<script>\(function\(\)\{var d=document\.getElementById\("photo-description"\).*?\}\)\(\);</script>', '', content, flags=re.DOTALL)

new_js = '<script>\n(function() {\n  var descPanel = document.getElementById("photo-description");\n  var descOpen = false;\n\n  function showDesc() {\n    if (!descPanel || !window.activeImg) return;\n    var img = window.activeImg;\n    descPanel.querySelector(".desc-title").textContent = img.dataset.title || "";\n    descPanel.querySelector(".desc-meta").textContent = (img.dataset.artist || "") + (img.dataset.year ? " · " + img.dataset.year : "");\n    descPanel.querySelector(".desc-body").textContent = img.dataset.description || "";\n    var g = document.querySelector(".photo-spotlight");\n    if (g) {\n      var panelW = Math.min(window.innerWidth * 0.3, 380);\n      var gap = 32;\n      var shift = (panelW + gap) / 2;\n      g.style.transform = g.style.transform + " translateX(-" + shift + "px)";\n      g._descShift = shift;\n      descPanel.style.width = panelW + "px";\n      var gr = g.getBoundingClientRect();\n      descPanel.style.left = (gr.right + gap) + "px";\n      descPanel.style.right = "auto";\n      descPanel.style.top = "50%";\n      descPanel.style.transform = "translateY(-50%)";\n    }\n    descPanel.classList.add("visible");\n    var cap = document.querySelector(".photo-caption-bar");\n    if (cap) cap.style.opacity = "0";\n    descOpen = true;\n  }\n\n  function hideDesc() {\n    if (!descPanel) return;\n    var g = document.querySelector(".photo-spotlight");\n    if (g && g._descShift) {\n      g.style.transform = g.style.transform.replace(" translateX(-" + g._descShift + "px)", "");\n      g._descShift = null;\n    }\n    descPanel.classList.remove("visible");\n    descPanel.style.left = "";\n    var cap = document.querySelector(".photo-caption-bar");\n    if (cap) cap.style.opacity = "1";\n    descOpen = false;\n  }\n\n  document.addEventListener("click", function(e) {\n    var g = document.querySelector(".photo-spotlight");\n    if (!g) return;\n    var gr = g.getBoundingClientRect();\n    var pr = descPanel ? descPanel.getBoundingClientRect() : null;\n    var insideGhost = e.clientX >= gr.left && e.clientX <= gr.right && e.clientY >= gr.top && e.clientY <= gr.bottom;\n    var insidePanel = pr && descOpen && e.clientX >= pr.left && e.clientX <= pr.right && e.clientY >= pr.top && e.clientY <= pr.bottom;\n    if (insideGhost || insidePanel) {\n      if (descOpen) { hideDesc(); } else { showDesc(); }\n      e.stopPropagation();\n    }\n  }, true);\n})();\n</script>'

content = content.replace('</body>', new_js + '\n</body>', 1)
open('index.html', 'w', encoding='utf-8').write(content)
print('Done')
